spring.application.name=olympic_ot_project

spring.datasource.url= ${url}
spring.datasource.username= ${username}
spring.datasource.password= ${password}

spring.jpa.hibernate.ddl-auto= validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${email}
spring.mail.password= ${email_password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

jwt.secret= ${secret_key}