workflows:
  ios-workflow:
    name: iOS Flutter Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    working_directory: olympic_it_project
    environment:
      # 🔥 Ép hệ thống dùng phiên bản Flutter mới nhất (Master) để gánh được đống thư viện siêu mới của bạn
      flutter: master
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          # Dùng lệnh này để tự động bỏ qua và sửa các lỗi khoảng trắng (nếu có) trên máy Mac
          flutter pub get --no-example
      - name: Build Flutter iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app