name: olympic_it_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  file_picker: ^6.1.1  # Để chọn tệp chung
  image_picker: ^1.0.7 # Để chuyên chọn ảnh/video
  video_player: ^2.8.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^10.3.1
  http: ^1.2.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
