name: olympic_it_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  flutter_secure_storage: ^10.3.1
  shared_preferences: ^2.5.5
  image_picker: ^1.1.2
  file_picker: ^10.3.3
  cached_network_image: ^3.4.1
  flutter_screenguard: ^2.0.1
  stomp_dart_client: ^3.0.1
  phone_state: ^4.0.1
  permission_handler: ^12.0.3
  video_player: ^2.8.2
  chewie: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/