import 'package:flutter/material.dart';
import 'package:plugin_platform_interface/plugin_platform_interface.dart';

import 'flutter_screenguard_method_channel.dart';

abstract class FlutterScreenguardPlatform extends PlatformInterface {
  /// Constructs a FlutterScreenguardPlatform.

  FlutterScreenguardPlatform() : super(token: _token);

  static final Object _token = Object();

  static FlutterScreenguardPlatform _instance =
      MethodChannelFlutterScreenguard();

  /// The default instance of [FlutterScreenguardPlatform] to use.
  ///
  /// Defaults to [MethodChannelFlutterScreenguard].
  static FlutterScreenguardPlatform get instance => _instance;

  /// Platform-specific implementations should set this with their own
  /// platform-specific class that extends [FlutterScreenguardPlatform] when
  /// they register themselves.
  static set instance(FlutterScreenguardPlatform instance) {
    PlatformInterface.verifyToken(instance, _token);
    _instance = instance;
  }

  /// activate a screenshot blocking with a color effect view (iOS 13+, Android 8+)
  /// [color] color of the background
  ///
  /// Throws a [PlatformException] if there were technical problems on native side
  /// (e.g. lack of relevant hardware).
  Future<void> register({
    required Color color,
  }) {
    throw UnimplementedError('register() has not been implemented.');
  }

  /// [iOS, Android] activate a screenshot blocking with a blurred effect view (iOS 13+, Android 8+)
  /// [radius] blur radius value number in between [15, 50], throws warning if smaller than 15 or bigger than 50,
  ///
  /// [localImagePath] Path to local image which is generated by Flutter,
  ///
  /// Throws a [PlatformException] if there were technical problems on native side
  /// (e.g. lack of relevant hardware).
  Future<void> registerWithBlurView({
    required num radius,
    String? localImagePath,
  }) {
    throw UnimplementedError(
        'registerWithBlurView() has not been implemented.');
  }

  /// [iOS 13+, Android 8+] activate a screenshot blocking with an image effect view
  /// [color] color of the background
  ///
  /// [uri] (required) uri of the image
  ///
  /// [width] (required) width of the image
  ///
  /// [height] (required) height of the image
  ///
  /// [alignment] Alignment of the image, default Alignment.center
  ///
  /// Throws a [PlatformException] if there were technical problems on native side
  Future<void> registerWithImage({
    required String uri,
    required double width,
    required double height,
    Color? color = Colors.black,
    Alignment? alignment,
    double? top,
    double? left,
    double? bottom,
    double? right,
  }) {
    throw UnimplementedError('register() has not been implemented.');
  }

  /// [Android 5+] activate a screenshot blocking without any effect (blur, image, color)
  ///
  /// Throws a [PlatformException] if there were technical problems on native side
  Future<void> registerWithoutEffect() {
    throw UnimplementedError(
        'registerWithoutEffect() has not been implemented.');
  }

  /// [iOS, Android] get screen guard logs
  Future<List<Map<String, dynamic>>> getScreenGuardLogs({
    required int maxCount,
  }) {
    throw UnimplementedError('getScreenGuardLogs() has not been implemented.');
  }

  /// [iOS, Android] stream for screenshot captured event
  Stream<Map<String, dynamic>> get onScreenshotCaptured {
    throw UnimplementedError(
        'onScreenshotCaptured getter has not been implemented.');
  }

  /// [iOS, Android] stream for screen recording captured event
  /// Returns a Map with:
  /// - isRecording: bool - whether recording started (true) or stopped (false)
  /// - activationStatus: Map with method (String) and isActivated (bool)
  Stream<Map<String, dynamic>> get onScreenRecordingCaptured {
    throw UnimplementedError(
        'onScreenRecordingCaptured getter has not been implemented.');
  }

  /// Initialize the screen guard with settings
  Future<void> initSettings({
    bool? enableCapture = false,
    bool? enableRecord = false,
    bool? enableContentMultitask = false,
    bool? displayOverlay = false,
    bool? displayScreenguardOverlayAndroid = true,
    int? timeAfterResume = 1000,
    bool? getScreenshotPath = false,
    int? limitCaptureEvtCount,
    bool? trackingLog = false,
  }) {
    throw UnimplementedError('initSettings() has not been implemented.');
  }

  /// unregister and deactivate all screenguard and listener
  /// Throws a [PlatformException] if there were technical problems on native side
  Future<void> unregister() {
    throw UnimplementedError('unregister() has not been implemented.');
  }
}
